<a href="https://colab.research.google.com/github/underratedicon/python-practice/blob/main/PandasPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 17, 28],
    'City': ['New york', 'San Francisco', 'Los Angelos', 'Alexandria'],
    'Salary': [100, 150, 200, 300]
}

df = pd.DataFrame(data)
df

      Name  Age           City  Salary
0    Alice   25       New york     100
1      Bob   30  San Francisco     150
2  Charlie   17    Los Angelos     200
3    David   28     Alexandria     300

In [5]:
df[['Name', 'Salary']]

      Name  Salary
0    Alice     100
1      Bob     150
2  Charlie     200
3    David     300

In [6]:
df.iloc[1]

Name                Bob
Age                  30
City      San Francisco
Salary              150
Name: 1, dtype: object

In [7]:
df['Age'].mean()

np.float64(25.0)

In [8]:
df['Salary'].mean()

np.float64(187.5)

In [9]:
print("The minimum salary is", df['Salary'].min())
print("The maximum salary is", df['Salary'].max())
print("The mean salary is", df['Salary'].mean())

The minimum salary is 100
The maximum salary is 300
The mean salary is 187.5

In [10]:
ndata = [10, 20, 30, 40, 50]
s = pd.Series(ndata)

print(s.min())
print(s.max())
print(s.mean())

10
50
30.0

In [11]:
df

      Name  Age           City  Salary
0    Alice   25       New york     100
1      Bob   30  San Francisco     150
2  Charlie   17    Los Angelos     200
3    David   28     Alexandria     300

In [13]:
df.head(2)

    Name  Age           City  Salary
0  Alice   25       New york     100
1    Bob   30  San Francisco     150

In [15]:
df.tail(2)

      Name  Age         City  Salary
2  Charlie   17  Los Angelos     200
3    David   28   Alexandria     300

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [18]:
df.describe().T

        count   mean        std    min    25%    50%    75%    max
Age       4.0   25.0   5.715476   17.0   23.0   26.5   28.5   30.0
Salary    4.0  187.5  85.391256  100.0  137.5  175.0  225.0  300.0

In [19]:
df

      Name  Age           City  Salary
0    Alice   25       New york     100
1      Bob   30  San Francisco     150
2  Charlie   17    Los Angelos     200
3    David   28     Alexandria     300

In [21]:
merged_df = pd.merge(df, df, on='Name')
merged_df

      Name  Age_x         City_x  Salary_x  Age_y         City_y  Salary_y
0    Alice     25       New york       100     25       New york       100
1      Bob     30  San Francisco       150     30  San Francisco       150
2  Charlie     17    Los Angelos       200     17    Los Angelos       200
3    David     28     Alexandria       300     28     Alexandria       300

In [23]:
df['New_Salary'] = df['Salary'].apply(lambda x: x * 1.2)
df

      Name  Age           City  Salary  New_Salary
0    Alice   25       New york     100       120.0
1      Bob   30  San Francisco     150       180.0
2  Charlie   17    Los Angelos     200       240.0
3    David   28     Alexandria     300       360.0

In [25]:
sorted_df = df.sort_values(by='Age')
sorted_df

      Name  Age           City  Salary  New_Salary
2  Charlie   17    Los Angelos     200       240.0
0    Alice   25       New york     100       120.0
3    David   28     Alexandria     300       360.0
1      Bob   30  San Francisco     150       180.0

In [27]:
df['is_adult'] = df['Age'].apply(lambda x: True if x >=18 else False)
df

      Name  Age           City  Salary  New_Salary  is_adult
0    Alice   25       New york     100       120.0      True
1      Bob   30  San Francisco     150       180.0      True
2  Charlie   17    Los Angelos     200       240.0     False
3    David   28     Alexandria     300       360.0      True

In [28]:
import kagglehub
path = kagglehub.dataset_download("akshaydattatraykhare/diabetes-dataset")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.1).
Downloading from https://www.kaggle.com/api/v1/datasets/download/akshaydattatraykhare/diabetes-dataset?dataset_version_number=1...

100%|██████████| 8.91k/8.91k [00:00<00:00, 15.1MB/s]

Extracting files...

In [30]:
import pandas as pd

import os

os.listdir(path)

['diabetes.csv']

In [31]:
df1 = pd.read_csv(path + "/diabetes.csv")

In [35]:
df1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [36]:
df1['Pregnancies'].unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14])

In [37]:
df1['Outcome'].unique()

array([1, 0])

In [38]:
correlation_matrix = df1.corr()
correlation_matrix

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [40]:
df1 = df1.rename(columns={'DiabetesPedigreeFunction': 'DPF'})
df1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1